export default{
	//将商品信息添加到state.cartArr中
	inCrement({commit},params){
		commit("add",params);
	},
	//购物车商品数量的统计
	totalShopNum({commit}){
		commit("shopNumTotal");
	},
	//修改商店的选中状态
	changeShopSelect({commit},params){
		commit("changeShopSelect",params);
	},
	//选中商家对总价的计算
	shopChangeCount({commit},params){
		commit("shopChangeCount",params);
	},
	//修改商品的选中状态
	goodsSelect({commit},params){
		commit("goodsSelect",params);
	},
	//选中商品对总价的计算
	goodsChangeCount({commit},params){
		commit("goodsChangeCount",params);
	},
	//总价的计算
	calculateAllMoney({commit},params){
		commit("calculate",params);
	},
	//商品+1的计算
	deleteNum({commit},params){
		commit("delNum",params);
	},
	//商品-1的计算
	addNum({commit},params){
		commit("addNum",params);
	},
	//删除商品的操作
	popShop({commit}){
		commit("moveShop");
	},
	//如果localStorage中存在购物车信息，则替换state中的cartArr
	replaceCartArr({commit},params){
		commit("changeCartArr",params);
	},
	replaceCartDetail({commit},params){
		commit("replaceCartDetail",params);
	},
	allSelect({commit},params){
		commit("allSelect",params);
	}
}